// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VibeCheck.DataAcces.Persistence;

#nullable disable

namespace VibeCheck.DataAcces.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814142012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VibeCheck.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.Follow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FollowingId");

                    b.HasIndex("FollowerId", "FollowingId")
                        .IsUnique();

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.SavedVenue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.HasIndex("UserId", "VenueId")
                        .IsUnique();

                    b.ToTable("SavedVenues");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<double>("AverageVibeScore")
                        .HasColumnType("double precision");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("TotalCheckIns")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("City");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeCheckComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VibeCheckEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VibeCheckEntryId");

                    b.ToTable("VibeCheckComments");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeCheckEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CrowdLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.Property<int>("VibeScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("VenueId");

                    b.ToTable("VibeCheckEntries");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeCheckEntryTag", b =>
                {
                    b.Property<Guid>("VibeCheckEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VibeTagId")
                        .HasColumnType("uuid");

                    b.HasKey("VibeCheckEntryId", "VibeTagId");

                    b.HasIndex("VibeTagId");

                    b.ToTable("VibeCheckEntryTags");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeCheckPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("VibeCheckEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VibeCheckEntryId");

                    b.ToTable("VibeCheckPhotos");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeCheckReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VibeCheckEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VibeCheckEntryId", "UserId")
                        .IsUnique();

                    b.ToTable("VibeCheckReactions");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VibeTags");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.Follow", b =>
                {
                    b.HasOne("VibeCheck.Domain.Entities.AppUser", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VibeCheck.Domain.Entities.AppUser", "FollowingUser")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("FollowingUser");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("VibeCheck.Domain.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.SavedVenue", b =>
                {
                    b.HasOne("VibeCheck.Domain.Entities.AppUser", "User")
                        .WithMany("SavedVenues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeCheck.Domain.Entities.Venue", "Venue")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.Venue", b =>
                {
                    b.HasOne("VibeCheck.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany("CreatedVenues")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeCheckComment", b =>
                {
                    b.HasOne("VibeCheck.Domain.Entities.AppUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeCheck.Domain.Entities.VibeCheckEntry", "VibeCheckEntry")
                        .WithMany("Comments")
                        .HasForeignKey("VibeCheckEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VibeCheckEntry");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeCheckEntry", b =>
                {
                    b.HasOne("VibeCheck.Domain.Entities.AppUser", "User")
                        .WithMany("VibeCheckEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeCheck.Domain.Entities.Venue", "Venue")
                        .WithMany("VibeCheckEntries")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeCheckEntryTag", b =>
                {
                    b.HasOne("VibeCheck.Domain.Entities.VibeCheckEntry", "VibeCheckEntry")
                        .WithMany("EntryTags")
                        .HasForeignKey("VibeCheckEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeCheck.Domain.Entities.VibeTag", "VibeTag")
                        .WithMany("EntryTags")
                        .HasForeignKey("VibeTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VibeCheckEntry");

                    b.Navigation("VibeTag");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeCheckPhoto", b =>
                {
                    b.HasOne("VibeCheck.Domain.Entities.VibeCheckEntry", "VibeCheckEntry")
                        .WithMany("Photos")
                        .HasForeignKey("VibeCheckEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VibeCheckEntry");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeCheckReaction", b =>
                {
                    b.HasOne("VibeCheck.Domain.Entities.AppUser", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeCheck.Domain.Entities.VibeCheckEntry", "VibeCheckEntry")
                        .WithMany("Reactions")
                        .HasForeignKey("VibeCheckEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VibeCheckEntry");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CreatedVenues");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Reactions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SavedVenues");

                    b.Navigation("VibeCheckEntries");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.Venue", b =>
                {
                    b.Navigation("SavedByUsers");

                    b.Navigation("VibeCheckEntries");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeCheckEntry", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("EntryTags");

                    b.Navigation("Photos");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("VibeCheck.Domain.Entities.VibeTag", b =>
                {
                    b.Navigation("EntryTags");
                });
#pragma warning restore 612, 618
        }
    }
}
